import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-variant': '#dae2fd',
        'on-secondary-fixed': '#002110',
        background: '#faf8ff',
        outline: '#737688',
        'surface-container-lowest': '#ffffff',
        'primary-fixed': '#dde1ff',
        'surface-tint': '#004ced',
        'surface-bright': '#faf8ff',
        'on-primary-container': '#dfe3ff',
        'inverse-primary': '#b7c4ff',
        'on-surface-variant': '#434656',
        'tertiary-fixed': '#ffdad5',
        surface: '#faf8ff',
        'inverse-surface': '#283044',
        'inverse-on-surface': '#eef0ff',
        'on-tertiary-container': '#ffddd8',
        'surface-dim': '#d2d9f4',
        error: '#ba1a1a',
        'on-tertiary-fixed-variant': '#930005',
        'on-secondary': '#ffffff',
        'primary-fixed-dim': '#b7c4ff',
        'on-primary-fixed': '#001452',
        'on-tertiary': '#ffffff',
        primary: '#003ec7',
        'outline-variant': '#c3c5d9',
        'tertiary-container': '#cc0d11',
        'on-primary': '#ffffff',
        'tertiary-fixed-dim': '#ffb4aa',
        'secondary-container': '#66fdac',
        'error-container': '#ffdad6',
        'on-secondary-container': '#007345',
        secondary: '#006d41',
        'surface-container-high': '#e2e7ff',
        'on-primary-fixed-variant': '#0038b6',
        tertiary: '#a10007',
        'on-secondary-fixed-variant': '#00522f',
        'primary-container': '#0052ff',
        'on-tertiary-fixed': '#410001',
        'secondary-fixed-dim': '#44e092',
        'surface-container-highest': '#dae2fd',
        'secondary-fixed': '#66fdac',
        'on-background': '#131b2e',
        'surface-container': '#eaedff',
        'on-surface': '#131b2e',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'surface-container-low': '#f2f3ff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        base: '8px',
        'container-padding-mobile': '16px',
        gutter: '24px',
        'stack-lg': '24px',
        'container-padding-desktop': '32px',
        'stack-md': '12px',
        'stack-sm': '4px',
      },
      fontFamily: {
        'body-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        display: ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'numeric-data': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '0', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        display: ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', letterSpacing: '0', fontWeight: '400' }],
        'numeric-data': ['20px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
      },
    },
  },
  plugins: [forms, containerQueries],
};
